exports.default = {
  $SITE_DESCRIPTION: 'Join an SA meeting anytime, anywhere! Choose from over 350 weekly SA meetings on Zoom, FreeConferenceCall, and other platforms!',
  $SITE_TITLE:'NextMeeting for SA',
  $SITE_PUBLIC_URL:'https://nextmeeting.org/275EE30A-220F-4FF2-A950-0ED2B5E4C257.html',
  $SITE_PROMO_BANNER_IMAGE: '0E54F15A-1E78-4E30-B568-A9BDE15E3C4B.jpg',
  $APPLE_TOUCH_ICON: 'apple-touch-icon.png',
  $FELLOWSHIP: 'SA',
  $FEEDBACK_EMAIL_ADDRESS: "sanewsenglish@gmail.com",
  $SOURCE_GOOGLE_SHEET_URL: 'https://docs.google.com/spreadsheets/d/1_QxT6VIm1HTLKSl71DtDqSMWVZYrdbqSl0WSF0Ch6g4/edit#gid=0',
  $ADD_NEW_MEETING_URL: 'https://docs.google.com/forms/d/e/1FAIpQLScOwdDsnTptb0NR3HuibXjAAT-qYGJwIUN2U1sIQobbMUAXSw/viewform',
  $THEME_LIGHT: 'theme-purple-light',
  $THEME_DARK: 'theme-purple-dark',
  $DEPLOY_ID: '275EE30A-220F-4FF2-A950-0ED2B5E4C257',
  $ANNOUNCEMENT_BAR_TEXT: 'Hey, welcome! Please keep this site and all meeting info within SA',
  $ANNOUNCEMENT_BAR_URL: '',
  $ANNOUNCEMENT_BAR_EMOJI: '😎',
}