exports.default = {
  $SITE_DESCRIPTION: 'Join an S-Anon meeting anytime, anywhere! Choose from over 90 weekly S-Anon meetings on Zoom, from all around the world!',
  $SITE_TITLE:'NextMeeting for S-Anon',
  $SITE_PUBLIC_URL:'https://nextmeeting.org/B0E7F18B-4CF5-49FF-BBD3-75E1CA52AA5E.html',
  $SITE_PROMO_BANNER_IMAGE: 'D049D811-DCD7-4417-B2C6-08FF77796C2B.jpg',
  $APPLE_TOUCH_ICON: 'apple-touch-icon__forest.png',
  $FELLOWSHIP: 'S-Anon',
  $FEEDBACK_EMAIL_ADDRESS: "sanonhope@gmail.com",
  $SOURCE_GOOGLE_SHEET_URL: 'https://docs.google.com/spreadsheets/d/1UJneS5GKFQSIy_iAfkLE21nRC_E8VzJ8diTT4Z3JnrA/edit?usp=sharing',
  $ADD_NEW_MEETING_URL: 'https://docs.google.com/forms/d/e/1FAIpQLScZRBsoNxRXyaBYZD6y-MZtEt1L63maHMyE1XonNoHt6PsklQ/viewform',
  $THEME_LIGHT: 'theme-forest-light',
  $THEME_DARK: 'theme-forest-dark',
  $DEPLOY_ID: 'B0E7F18B-4CF5-49FF-BBD3-75E1CA52AA5E',
 $ANNOUNCEMENT_BAR_TEXT: 'Welcome to our brand new Zoom meeting site! Please keep this site and all meeting info within S-Anon.',
 $ANNOUNCEMENT_BAR_URL: '',
 $ANNOUNCEMENT_BAR_EMOJI: '🎉',
}